                               Libraries

In [39]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns

                                Load Dataset

In [2]:
def load_data(file_path):
    df = pd.read_excel(file_path)
    return df

In [6]:
file_path = '../../data/raw_data.xlsx'
df = load_data(file_path)
df.head()

,Brand,Model,Year,EngineSize,Fuel,Transmission,Mileage,Doors,OwnerCount,Price
0,Kia,Rio,2020,4.2,Diesel,Manual,289944,3,5,8501
1,Chevrolet,Malibu,2012,2.0,Hybrid,Automatic,5356,2,3,12092
2,Mercedes,GLA,2020,4.2,Diesel,Automatic,231440,4,2,11171
3,Audi,Q5,2023,2.0,Electric,Manual,160971,2,1,11780
4,Volkswagen,Golf,2003,2.6,Hybrid,Semi-Automatic,286618,3,3,2867

In [10]:
X = df.drop('Price', axis=1)
y = df['Price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 42)

df = X_train.copy()
df['Price'] = y_train

                          Remove Extra Columns
In this project we dont have any unnecessary columns so we leave them as they are,

Columns Typecasting
Here, we should make sure about the datatype of each column.

In [11]:
print(df.dtypes)

Brand            object
Model            object
Year              int64
EngineSize      float64
Fuel             object
Transmission     object
Mileage           int64
Doors             int64
OwnerCount        int64
Price             int64
dtype: object

                    Handling Missing values

In [12]:
for col in df.columns:
    number_null = df.loc[: , col].isnull().sum()
    perc_null = (number_null / df.shape[0]) *100
    print('{} - {} -%{}'.format(col,number_null, round(perc_null,3)))

Brand - 0 -%0.0
Model - 0 -%0.0
Year - 0 -%0.0
EngineSize - 0 -%0.0
Fuel - 0 -%0.0
Transmission - 0 -%0.0
Mileage - 0 -%0.0
Doors - 0 -%0.0
OwnerCount - 0 -%0.0
Price - 0 -%0.0

                Handles a Duplicates rows

In [13]:
duplicate_rows = df.duplicated()

if duplicate_rows.any():
    print("There is Duplicate.")
else:
    print("No duplications.")

No duplications.

Numerical sanity check

first of all, i declare all numerical variables.
• Year
• Engine Size
• Mileage
• Doors
• Owner Count
• Price

In [14]:
numeric_columns = df.select_dtypes(include=['int64', 'float64']).columns.tolist()

In [15]:
df[numeric_columns].describe()

,Year,EngineSize,Mileage,Doors,OwnerCount,Price
count,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000
mean,2011.520375,2.996887,149477.003250,3.503625,2.991875,8828.745250
std,6.897792,1.153237,86613.284937,1.111482,1.420849,3132.164285
min,2000.000000,1.000000,25.000000,2.000000,1.000000,2000.000000
25%,2006.000000,2.000000,74192.250000,3.000000,2.000000,6604.750000
50%,2012.000000,3.000000,150069.500000,4.000000,3.000000,8829.000000
75%,2017.000000,4.000000,224292.750000,4.000000,4.000000,11071.000000
max,2023.000000,5.000000,299947.000000,5.000000,5.000000,18301.000000

This results shows all data are in correct range and logical range.

Categorical sanity check
First of all, i declared all categorical variables.
• Brand
• Model
• Fuel
• Transmission

In [16]:
cat_columns = df.select_dtypes(exclude=['int64','float64']).columns.tolist()

Then, we must makes sure about the psooible categories for each other.

In [19]:
def Cat_Checker(CatIndex):
    values = np.sort(df[cat_columns[CatIndex]].unique())
    return cat_columns[CatIndex], values

In [23]:
Cat_Checker(0)

('Brand',
 array(['Audi', 'BMW', 'Chevrolet', 'Ford', 'Honda', 'Hyundai', 'Kia',
        'Mercedes', 'Toyota', 'Volkswagen'], dtype=object))

In [24]:
Cat_Checker(1)

('Model',
 array(['3 Series', '5 Series', 'A3', 'A4', 'Accord', 'C-Class', 'CR-V',
        'Camry', 'Civic', 'Corolla', 'E-Class', 'Elantra', 'Equinox',
        'Explorer', 'Fiesta', 'Focus', 'GLA', 'Golf', 'Impala', 'Malibu',
        'Optima', 'Passat', 'Q5', 'RAV4', 'Rio', 'Sonata', 'Sportage',
        'Tiguan', 'Tucson', 'X5'], dtype=object))

In [25]:
Cat_Checker(2)

('Fuel', array(['Diesel', 'Electric', 'Hybrid', 'Petrol'], dtype=object))

In [26]:
Cat_Checker(3)

('Transmission',
 array(['Automatic', 'Manual', 'Semi-Automatic'], dtype=object))

                 CHECKPOINT

In [27]:
%store X_test
%store y_test
%store df
%store numeric_columns
%store cat_columns

Stored 'X_test' (DataFrame)
Stored 'y_test' (Series)
Stored 'df' (DataFrame)
Stored 'numeric_columns' (list)
Stored 'cat_columns' (list)